In [2]:
pip install  notebook


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
 import numpy as np


In [10]:
random_int_array = np.random.randint(1, 10, size=(2, 2))

In [11]:
random_int_array

array([[8, 7],
       [2, 8]])

In [12]:
random_int_array = np.random.randint(1, 50, size=(10))

In [13]:
random_int_array

array([44,  1,  5,  8, 20,  1, 11,  6,  3, 36])

In [16]:
random_int_array = np.random.randint(10, 100, size=(2,5))
random_int_array.shape

(2, 5)

In [17]:
random_int_array = np.random.randint(1, 50, size=(10))
np.mean(random_int_array )

31.8

In [22]:
random_int_array1 = np.random.randint(1,50, size=(2,3))
random_int_array2 = np.random.randint(1,50, size=(2,3))
num=random_int_array1+random_int_array2
np.mean(num)

50.0

In [25]:
random_int_array1 = np.random.randint(1,100, size=(20))
filtered_arr =random_int_array1[random_int_array1>50]
filtered_arr

array([51, 71, 54, 53, 89, 85, 87, 55, 54, 77])